// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCacIZr7P68kTLr2uN_OOqOdewGrmATF8E',
    appId: '1:1016213844517:web:afa90f4bdc72d6bce845cc',
    messagingSenderId: '1016213844517',
    projectId: 'recipebudgetfinderapp67',
    authDomain: 'recipebudgetfinderapp67.firebaseapp.com',
    storageBucket: 'recipebudgetfinderapp67.firebasestorage.app',
    measurementId: 'G-H33HJ6TYCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZeJBq4eCNVY6HXEy03ROt9A31g_5cpR4',
    appId: '1:1016213844517:android:90868ec173e4fa2ae845cc',
    messagingSenderId: '1016213844517',
    projectId: 'recipebudgetfinderapp67',
    storageBucket: 'recipebudgetfinderapp67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGZj9zxfOD57DLQHCPs9FoOs8xwXHjZSo',
    appId: '1:1016213844517:ios:c38ef55df09ced9ee845cc',
    messagingSenderId: '1016213844517',
    projectId: 'recipebudgetfinderapp67',
    storageBucket: 'recipebudgetfinderapp67.firebasestorage.app',
    iosBundleId: 'com.deveraestrera.pesoPantry',
  );
}
